#server:
#  port: 8098
#
#spring:
#  application:
#    name: WebCoCo
#
#
#

spring:
  r2dbc:
   url: r2dbc:pool:mysql://localhost:3306/WebCoCo
   username: root
   password: KHANH2005t

  # flyway config
  datasource:
    url: r2dbc:pool:mysql://localhost:3306/WebCoCo
    username: root
    password: KHANH2005t
#    driver-class-name: com.mysql.cj.jdbc.Driver


#jwt:
#  expiration: 2592000
#  expiration-refresh-token: 5184000
#  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
#
#
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 100MB
#
#api:
#  prefix: /api/v1
